MvcKutuphane/Controllers/AyarlarController.cs
using MvcKutuphane.Models.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcKutuphane.Controllers
{
    public class AyarlarController : Controller
    {
        // GET: Ayarlar
        DBKUTUPHANEEntities db = new DBKUTUPHANEEntities();
        public ActionResult Index()
        {       
            return View();
        }

        public ActionResult Index2()
        {
            var kullanicilar = db.TBLADMIN.ToList();
            return View(kullanicilar);
        }
        [HttpGet]
        public ActionResult YeniAdmin()
        {
            return View();
        }
        [HttpPost]
        public ActionResult YeniAdmin(TBLADMIN t)
        {
            db.TBLADMIN.Add(t);
            db.SaveChanges();
            return RedirectToAction("Index2");
        }
        public ActionResult AdminSil(int id)
        {
            var admin = db.TBLADMIN.Find(id);
            db.TBLADMIN.Remove(admin);
            db.SaveChanges();
            return RedirectToAction("Index2");
        }
        [HttpGet]
        public ActionResult AdminGuncelle(int id)
        {
            var admin = db.TBLADMIN.Find(id);
            return View("AdminGuncelle", admin);
        }
        [HttpPost]
        public ActionResult AdminGuncelle(TBLADMIN p)
        {
            var admin = db.TBLADMIN.Find(p.ID);
            admin.Kullanici = p.Kullanici;
            admin.Sifre = p.Sifre;
            admin.Yetki = p.Yetki;
            db.SaveChanges();
            return RedirectToAction("Index2");

        }
    }
}

MvcKutuphane/Views/Ayarlar/AdminGuncelle.cshtml
@model MvcKutuphane.Models.Entity.TBLADMIN

@{
    ViewBag.Title = "AdminGuncelle";
    Layout = "~/Views/Shared/Layout.cshtml";
}

@using (Html.BeginForm("AdminGuncelle", "Ayarlar", FormMethod.Post))
{
    <div style="margin-bottom:15px"></div>
    <div class="form-group">
        @Html.LabelFor(k => k.ID)
        @Html.TextBoxFor(k => k.ID, new { @class = "form-control" })
        <br />
        @Html.LabelFor(k => k.Kullanici)
        @Html.TextBoxFor(k => k.Kullanici, new { @class = "form-control" })
        <br />
        @Html.LabelFor(k => k.Sifre)
        @Html.TextBoxFor(k => k.Sifre, new { @class = "form-control" })
        <br />
        @Html.LabelFor(k => k.Yetki)
        @Html.TextBoxFor(k => k.Yetki, new { @class = "form-control" })
    </div>
    <div>
        <button class="btn btn-warning">Güncelle</button>
    </div>
}

MvcKutuphane/Views/Ayarlar/Index2.cshtml
@using MvcKutuphane.Models.Entity
@model List<TBLADMIN>
@{
    ViewBag.Title = "Index2";
    Layout = "~/Views/Shared/Layout.cshtml";
}
<link rel="stylesheet" href="/AdminLTE-3.0.4/plugins/fontawesome-free/css/all.min.css">
<script src="~/Scripts/jquery-3.4.1.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>
<br />
<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>Kullanıcı</th>
        <th>Yetki</th>
        <th>Sil</th>
        <th>Düzenle</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.ID</td>
            <td>@item.Kullanici</td>
            <td>@item.Yetki</td>
            <td>
                <a class="btn btn-info btn-sm" href="/Ayarlar/AdminGuncelle/@item.ID">
                    <i class="fas fa-pencil-alt">
                    </i>
                    Düzenle
                </a>
            </td>
            <td>
                <a class="btn btn-danger btn-sm" href="/Ayarlar/AdminSil/@item.ID">
                    <i class="fas fa-trash">
                    </i>
                    Sil
                </a>
            </td>
        </tr>
    }
</table>
<button class="btn btn-primary" data-toggle="modal" data-target="#Modal1">Yeni Admin Ekle</button>

<div class="modal" id="Modal1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="modal-title">Admin Ekleme Paneli</h2>
            </div>
            <form method="post" action="/Ayarlar/YeniAdmin/">
                <div class="modal-body">
                    <label>Kullanıcı Adı</label>
                    <input type="text" name="Kullanici" class="form-control" />
                    <br />
                    <label>Şifre</label>
                    <input type="text" name="Sifre" class="form-control" />
                    <br />
                    <label>Yetki</label>
                    <input type="text" name="Yetki" class="form-control" />
                    <br />
                    <button class="btn btn-success">Kaydet</button>
                </div>
            </form>
        </div>
    </div>
</div>